name: Update Trophies

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: logusivam
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: tokyonight
          no-frame: true
          no-bg: false
          column: 7
          row: 1
          margin-w: 15
          margin-h: 15
          output_path: ./trophy.svg

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add trophy.svg
          git diff-index --quiet HEAD || git commit -m "Update profile trophies"
          git push
